apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: python-pyramid-postgres
    service: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: testpw
  init_sql.sql: "CREATE ROLE testuser LOGIN SUPERUSER PASSWORD 'testpassword';\n\nDROP TABLE IF EXISTS example;\n\nCREATE TABLE example (id INT,json_col JSON,json_array_col JSON,jsonb_col JSONB,jsonb_array_col JSONB);"
  seed_data.sql: "INSERT INTO example VALUES (1,'[1,2,3]'::json,'[{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}]'::json,'[1,2,3]'::jsonb,'[{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}]'::jsonb);\n\nINSERT INTO example VALUES (2,'[1,2,3]'::json,'[{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}]'::json,'[1,2,3]'::jsonb,'[{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}]'::jsonb);\n\nINSERT INTO example SELECT id, json_col, json_array_col, jsonb_col, jsonb_array_col FROM json_populate_record (NULL::example,'{\"id\": 3,\"json_col\": {\"name\": \"bob\", \"age\": 111},\"json_array_col\": [{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}],\"jsonb_col\": {\"name\": \"sarah\", \"age\": 2222},\"jsonb_array_col\": [{\"id\": 0, \"name\": \"a\"},{\"id\": 1, \"name\": \"a\"},{\"id\": 2, \"name\": \"c\"}]}');"